
const ores = [
    'Veldspar',
    'Scordite',
    'Pyroxeres',
    'Plagioclase',
    'Omber',
    'Kernite',
    'Jaspet',
    'Hemorphite',
    'Hedbergite',
    'Spodumain',
    'Dark Ochre',
    'Gneiss',
    'Crokite',
    'Bistot',
    'Arkonor',
    'Mercoxit'
];

const minerals = [
    'Tritanium',
    'Pyerite',
    'Mexallon',
    'Isogen',
    'Nocxium',
    'Zydrine',
    'Megacyte',
    'Morphite'
];

const planetary = [
    'Lustering Alloy',
    'Sheen Compound',
    'Gleaming Alloy',
    'Condensed Alloy',
    'Precious Alloy',
    'Motley Compound',
    'Fiber Composite',
    'Lucent Compound',
    'Opulent Compound',
    'Glossy Compound',
    'Crystal Compound',
    'Dark Compound',
    'Reactive Gas',
    'Noble Gas',
    'Base Metals',
    'Heavy Metals',
    'Noble Metals',
    'Reactive Metals',
    'Toxic Metals',
    'Industrial Fibers',
    'Supertensile Plastics',
    'Polyaramids',
    'Coolant',
    'Condensates',
    'Construction Blocks',
    'Nanites',
    'Silicate Glass',
    'Smartfab Units',
    'Heavy Water',
    'Suspended Plasma',
    'Liquid Ozone',
    'Ionic Solutions',
    'Oxygen Isotopes',
    'Plasmoids'
];

const salvage = [
    'Metal Scraps',
    'Reinforced Metal Scraps',
    'Charred Micro Circuit',
    'Fried Interface Circuit',
    'Tripped Power Circuit',
    'Smashed Trigger Unit',
    'Damaged Close In Weapon System',
    'Scorched Telemetry Processor',
    'Contaminated Lorentz Fluid',
    'Conductive Polymer',
    'Contaminated Nanite Polymer',
    'Defective Current Pump'
];

const datacores = [
    'Amarrian Starship Engineering',
    'Electromagnetic Physics',
    'Gallentean Starship Engineering',
    'High Energy Physics',
    'Rocket Science',
    'Mechanical Engineering',
    'Laser Physics',
    'Caldari Starship Engineering',
    'Minmatar Starship Engineering'
];

const wrecks = [
    'Lv4 Amarr Ship Debris',
    'Lv5 Amarr Ship Debris',
    'Lv6 Amarr Ship Debris',
    'Lv7 Amarr Ship Debris',
    'Lv8 Amarr Ship Debris',
    'Lv9 Amarr Ship Debris',
    'Lv10 Amarr Ship Debris',
    'Lv4 Caldari Ship Debris',
    'Lv5 Caldari Ship Debris',
    'Lv6 Caldari Ship Debris',
    'Lv7 Caldari Ship Debris',
    'Lv8 Caldari Ship Debris',
    'Lv9 Caldari Ship Debris',
    'Lv10 Caldari Ship Debris',
    'Lv4 Gallente Ship Debris',
    'Lv5 Gallente Ship Debris',
    'Lv6 Gallente Ship Debris',
    'Lv7 Gallente Ship Debris',
    'Lv8 Gallente Ship Debris',
    'Lv9 Gallente Ship Debris',
    'Lv10 Gallente Ship Debris',
    'Lv4 Minmatar Ship Debris',
    'Lv5 Minmatar Ship Debris',
    'Lv6 Minmatar Ship Debris',
    'Lv7 Minmatar Ship Debris',
    'Lv8 Minmatar Ship Debris',
    'Lv9 Minmatar Ship Debris',
    'Lv10 Minmatar Ship Debris',
    'Small Damaged ORE Hull',
    'Medium Damaged ORE Hull',
    'Large Damaged ORE Hull',
    'Guristas Ship Debris',
    'Sansha Ship Debris',
    'Blood Raider Ship Debris',
    'Angel Ship Debris',
    'Serpentis Ship Debris',
    'SOE Ship Debris',
    'Mordus Legion Ship Debris',
    'Small Damaged InterBus Hull',
    'Medium Damaged InterBus Hull',
    'Large Damaged InterBus Hull'
];

module.exports = {
    ores: ores,
    minerals: minerals,
    planetary: planetary,
    salvage: salvage,
    datacores: datacores,
    wrecks: wrecks
};
